Query:
  type: object
  config:
    fields:
      store:
        type: "Store"
        args:
          id:
            type: "Int!"
        resolve: "@=resolver('store', [args['id']])"

      stores:
        type: "[Store]"
        resolve: "@=resolver('stores')"
